---
galaxy_info:
  role_name: kubectl
  author: ericsysmin
  description: Role to install kubectl
  company: Avi Networks
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - kubectl
    - ubuntu
    - centos
    - redhat
    - kubernetes
    - k8s
dependencies: []
