---
galaxy_info:
  author: ericsysmin
  role_name: kompose
  description: Role to install kompose on linux systems
  company: Avi Networks
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - kompose
    - ubuntu
    - centos
    - kubernetes
    - k8s
dependencies: []
